# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coffee.Rent
description: > # this means to ignore newlines until "baseurl:"
  <i> <b>Coffee Rent</b> [n] </i> : Coffee bought in order to validate spending a prolonged period of time in a cafe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coffee.rent" # the base hostname & protocol for your site
twitter_username: CoffeeRent

# Build settings
markdown: kramdown
